name: Test

on:
    push:
        branches:
            - main

jobs:
     test:
        name: Run Tests with Python 3.8
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.8
            - run: python --version
            - run: pip install -r requirements.txt
            - run: pytest
            